

services:
  dispatcher:
    build:
      context: .
      dockerfile: containers/dispatcher/Dockerfile
    volumes:
      - usage-data:/app/data
    restart: always
    ports:
      - "8081:8081"
    networks:
      default:
        aliases:
          - ditto-cluster

  driver:
    build:
      context: .
      dockerfile: containers/driver/Dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - dispatcher  # Ensure the dispatcher is up before starting the driver
    networks:
      default:
        aliases:
          - ditto-cluster

  model:
    build:
      context: .
      dockerfile: containers/model/Dockerfile
    restart: always
    ports:
      - "65432:65432"  
      - "65433:65433"
    networks:
      default:
        aliases:
          - ditto-cluster

volumes:
  usage-data: