version: '3.8'

services:
  dispatcher:
    build:
      context: .
      dockerfile: containers/dispatcher/Dockerfile
    volumes:
      - usage-data:/app/data
    restart: always
    ports:
      - "8080:8080"  # Expose port 8080 for external access
    networks:
      - app-network

  driver:
    build:
      context: .
      dockerfile: containers/driver/Dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - dispatcher  # Ensure the dispatcher is up before starting the driver
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  usage-data: