include:
  - ditto/docker-compose.yml
  - gateway/docker-compose.yml

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - '1883:1883'
    networks:
      default:
        aliases:
          - mosquitto
    environment:
      - TZ=Europe/Rome
    logging:
      options:
        max-size: 50m
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config:ro
    healthcheck:
      test: [ "CMD", "mosquitto_pub", "-h", "localhost", "-t", "healthcheck", "-m", "test" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
volumes:
  usage-data: